### ISSUE TITLE
Why don't provide whole pageInfo record to hook?

### ISSUE THREAD

**Issue by tpinne** [sypets/page_callouts#1]
Hi,

great little extension at the right time for me. But why do you only provide selected fields from the page record and not all?

I would like to show a message based on specific field of the current page record. At the moment I would have to query the database again for information which is already available. This is imho unnecessary?!

Would like to hear your comment on that decision.

Best regards
tpinne

**Comment by sypets** [comment]
@tpinne Yes, I agree. Should be fairly easy to change.

**Comment by sypets** [comment]
Fixed with #2
