### ISSUE TITLE
Add the extension in Crowdin so we can offer translation

### ISSUE THREAD

**Issue by gaumondp** [sypets/page_callouts#11]
The title says it all.

You can make me responsible for French translation.

**Comment by sypets** [comment]
I checked again, but there are almost no texts in the extension. There is

* 1 item in the extension configuration
* As of right now it is using the following language keys from the core: 
   *  LLL:EXT:core/Resources/Private/Language/locallang_core.xlf:labels.close (if close button is used)

Once there is more text, I would upload. I will add a language file now for the extension configuration and use that.
