### ISSUE TITLE
Compactibility to TYPO 3 12.4 LTS

### ISSUE THREAD

**Issue by Epoche-Napoleon** [sypets/page_callouts#17]
Is a compactibility to TYPO3 12.4 LTS planed?

**Comment by sypets** [comment]
Absolutely. Will be coming (hopefully this week) ...

**Comment by sypets** [comment]
Is merged: https://github.com/sypets/page_callouts/pull/18

You should update to >= 4.0.0 for TYPO3 v12. I am also preparing a fix in brofix for v12: https://github.com/sypets/brofix/pull/295
